theme: minima
title: "Graphia - Clarity from Complexity"
header_pages:
  - download.md
  - example-data.md
  - userguide.md
collections_dir: guide
collections:
  section1:
    output: true
    permalink: /guide/:path/
  section2:
    output: true
    permalink: /guide/:path/
  section3:
    output: true
    permalink: /guide/:path/
  section4:
    output: true
    permalink: /guide/:path/
